# Generated by Django 6.0.3 on 2026-03-23 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя артиста')),
                ('photo', models.URLField(blank=True, max_length=500, verbose_name='Фото')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('genre', models.CharField(blank=True, max_length=100, verbose_name='Жанр')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Артист',
                'verbose_name_plural': 'Артисты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название песни')),
                ('album', models.CharField(blank=True, max_length=300, verbose_name='Альбом')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('lyrics', models.TextField(blank=True, verbose_name='Текст песни')),
                ('youtube_url', models.URLField(blank=True, max_length=500, verbose_name='YouTube ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.artist', verbose_name='Артист')),
            ],
            options={
                'verbose_name': 'Песня',
                'verbose_name_plural': 'Песни',
                'ordering': ['-year', 'title'],
            },
        ),
    ]
